id: P5AEF5464
initial_creation_type: input
source_metadata:
  title: Trulshik Rinpoche Series
  language: nl
  description: Texts by and about Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö ('khrul
    zhig ngag dbang chos kyi blo gros, 1924–2011), one of the teachers of His Holiness
    the Fourteenth Dalai Lama.
  volume:
    437c6ab4f20d41ea8fece325922e302a:
      title: Advice for Retreat
      parent: Advice
    819d1618c2e44d558f966357a18ae425:
      title: Advice for Tenzin Jamchen
      parent: Advice
    817d693330284c99acc015db0e4b6b21:
      title: Advice in Four Lines
      parent: Advice
    2d6391e33d384417acd00eee11735808:
      title: A Prayer for Translators
      parent: Aspiration Prayers
    e608ba2eb1bc45d2ae7e3e76dea1dc76:
      title: A Prayer for the Spread of Kyabje Dilgo Khyentse Rinpoche’s Termas
      parent: Aspiration Prayers
    8eeaadc29f7146529051319956d2cd50:
      title: Prayer of the View, Meditation and Conduct
      parent: Aspiration Prayers
    320806b67b0944f9880e9efa262b90a3:
      title: Profound Prayer of Aspiration
      parent: Aspiration Prayers
    f60f92b12c9a44018ddb488b1aa5b10d:
      title: 'The Quintessential Blessing: A Guru Yoga'
      parent: Guru Yoga
    ed67c90fb161470fbd640c2815ef3b6d:
      title: 'Granting the Wish for Immortality: A Prayer for the Long Life of Dzarong
        Trulshik Rinpoche, the Representative of Guru Rinpoche'
      parent: Long Life Prayers
    324d4be2929b40b0901a17f88bad6430:
      title: Long Life Prayer for Alak Zenkar Rinpoche
      parent: Long Life Prayers
    f4b3fbce8cd844559a48d697be8ef969:
      title: Long Life Prayer for Kyabje Dzarong Trulshik Rinpoche
      parent: Long Life Prayers
    d5866de51e1d40649fb28272229afac4:
      title: Long Life Prayer for Lodi Gyari Rinpoche
      parent: Long Life Prayers
    92ab7eba567f4490a00be9aacd3c0a58:
      title: Long Life Prayer for Mayum Tsering Wangmo
      parent: Long Life Prayers
    f80673643c08402a9a76575dc58da0a2:
      title: Prayer for the Long Life of Chökyi Nyima Rinpoche
      parent: Long Life Prayers
    1f8ed2e5eb144f429ca0370f34a6a26e:
      title: Prayer for the Long Life of Dilgo Khyentsé II of Shechen, Urgyen Tenzin
        Jigme Lhundrup
      parent: Long Life Prayers
    3d0e3c915eda451e970d85e5714b4500:
      title: Prayer for the Long Life of His Holiness the Fourteenth Dalai Lama
      parent: Long Life Prayers
    5849b581c6f845b48e617a294cb29e11:
      title: Prayer for the Long Life of Sogyal Rinpoche—chimé kunnyé
      parent: Long Life Prayers
    505c3b416a8e42f0947e8d59fef1e6ef:
      title: Prayer for the Long Life of Sogyal Rinpoche—sönam jewé
      parent: Long Life Prayers
    a050e0dc15ca45588e783adc0487a967:
      title: Prayer for the Long Life of Taklung Tsetrul Rinpoche
      parent: Long Life Prayers
    5acf39d8a0ec44e385692493f956ad4a:
      title: The Attainment of Immortality
      parent: Long Life Prayers
    6f554ccc4724445c87f7a7f8c379e3a2:
      title: A Homage to His Holiness the Dalai Lama
      parent: Praise
    06fa8371f1e14e17a85e67776d673373:
      title: Verses of Homage
      parent: Praise
    390974c50189492082ebe214100ebe77:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: Praise
    bf57aab2db58477c864aad9bb47840d0:
      title: A Record of the Successive Incarnations
      parent: Prayers
    c7cd4da3a46944b98e98d92b2f5ddfb8:
      title: 'Gateway for the Faithful: A Supplication Recalling the Lives and Liberation
        of Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö'
      parent: Prayers
    a5f8fb1040ef464789df38f77f27c9fc:
      title: A Brief Daily Practice of Damdrip Nyepa Kunsel
      parent: Sādhanas
    9a4674e954ff43b1b029635863a0ee38:
      title: Prayer for the Swift Rebirth of Kyabjé Trulshik Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T01:52:59.294652'
last_modified_at: '2022-03-01T01:52:59.294656'
